"use client";

import { motion } from "framer-motion";
import { CheckCircle, Sparkles, Bot, Zap, Image, Type } from "lucide-react";

const watermarkTypes = [
  {
    icon: Bot,
    name: "AI/ML Detection Engine",
    examples: [
      "Pattern Recognition",
      "Computer Vision",
      "Text Analysis",
      "Anomaly Detection",
    ],
    description:
      "Advanced AI algorithms detect ANY watermark type automatically",
    color: "from-purple-500 to-pink-500",
  },
  {
    icon: Sparkles,
    name: "All Platform Watermarks",
    examples: [
      "Gamma",
      "Gemini",
      "ChatGPT",
      "VoxDeck.ai",
      "Canva",
      "Figma",
      "50+ More",
    ],
    description: "Comprehensive database of AI platforms and design tools",
    color: "from-blue-500 to-cyan-500",
  },
  {
    icon: Type,
    name: "Smart Text Detection",
    examples: ["Made with...", "Generated by...", "DRAFT", "SAMPLE", "URLs"],
    description: "Intelligent text analysis with context understanding",
    color: "from-green-500 to-emerald-500",
  },
  {
    icon: Image,
    name: "Visual Watermarks",
    examples: ["Logos", "Symbols", "Brand marks", "Signatures", "Stamps"],
    description: "Computer vision detects image-based watermarks",
    color: "from-yellow-500 to-orange-500",
  },
  {
    icon: Zap,
    name: "Background Reconstruction",
    examples: [
      "Intelligent Filling",
      "Texture Synthesis",
      "Edge Preservation",
      "Seamless Blending",
    ],
    description: "Advanced inpainting makes removal completely invisible",
    color: "from-red-500 to-pink-500",
  },
  {
    icon: Sparkles,
    name: "Unknown Watermarks",
    examples: [
      "Custom branding",
      "New AI tools",
      "Proprietary marks",
      "Future platforms",
    ],
    description: "ML anomaly detection finds watermarks not in our database",
    color: "from-orange-500 to-red-500",
  },
];

export function WatermarkTypes() {
  return (
    <section className="py-20">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.8 }}
        className="text-center mb-16"
      >
        <h2 className="text-4xl md:text-5xl font-bold text-white mb-6">
          Advanced AI/ML Watermark Detection
        </h2>
        <p className="text-xl text-gray-300 max-w-3xl mx-auto">
          Production-ready AI system that detects and removes ANY watermark type
          using multiple machine learning algorithms and intelligent background
          reconstruction.
        </p>
      </motion.div>

      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8 mb-16">
        {watermarkTypes.map((type, index) => (
          <motion.div
            key={type.name}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: index * 0.1 }}
            whileHover={{ y: -5, scale: 1.02 }}
            className="card group hover:glow-border transition-all duration-300"
          >
            <div className="mb-6">
              <div
                className={`w-16 h-16 rounded-2xl bg-gradient-to-r ${type.color} p-4 mb-4 group-hover:scale-110 transition-transform duration-300`}
              >
                <type.icon className="w-8 h-8 text-white" />
              </div>
              <h3 className="text-xl font-bold text-white mb-3">{type.name}</h3>
              <p className="text-gray-400 mb-4 leading-relaxed">
                {type.description}
              </p>
              <div className="space-y-2">
                <p className="text-sm text-gray-500 font-medium">Examples:</p>
                <div className="flex flex-wrap gap-2">
                  {type.examples.map((example, idx) => (
                    <span
                      key={idx}
                      className="px-2 py-1 bg-gray-800/50 rounded-full text-xs text-gray-300 border border-gray-700"
                    >
                      {example}
                    </span>
                  ))}
                </div>
              </div>
            </div>
          </motion.div>
        ))}
      </div>

      {/* Detection Process */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.8, delay: 0.6 }}
        className="card max-w-4xl mx-auto"
      >
        <h3 className="text-2xl font-bold text-white mb-8 text-center">
          Multi-Layer AI Detection Pipeline
        </h3>

        <div className="grid md:grid-cols-4 gap-6">
          {[
            {
              step: "1",
              title: "Multi-Method Detection",
              description:
                "Text analysis, computer vision, pattern matching, ML anomaly detection",
              icon: "🔍",
            },
            {
              step: "2",
              title: "Confidence Scoring",
              description:
                "AI calculates removal confidence using multiple factors",
              icon: "🧠",
            },
            {
              step: "3",
              title: "Intelligent Removal",
              description: "Advanced inpainting with background reconstruction",
              icon: "✨",
            },
            {
              step: "4",
              title: "Seamless Integration",
              description:
                "Post-processing ensures invisible, natural-looking results",
              icon: "✅",
            },
          ].map((process, index) => (
            <motion.div
              key={process.step}
              initial={{ opacity: 0, x: -20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.5, delay: 0.8 + index * 0.1 }}
              className="text-center"
            >
              <div className="w-16 h-16 bg-gradient-to-r from-primary-500 to-purple-500 rounded-full flex items-center justify-center text-2xl mb-4 mx-auto">
                {process.icon}
              </div>
              <h4 className="text-lg font-bold text-white mb-2">
                {process.title}
              </h4>
              <p className="text-gray-400 text-sm">{process.description}</p>
            </motion.div>
          ))}
        </div>
      </motion.div>

      {/* Success Rate */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.8, delay: 1.0 }}
        className="mt-16 text-center"
      >
        <div className="inline-flex items-center space-x-2 bg-green-500/20 border border-green-500/30 rounded-full px-6 py-3">
          <CheckCircle className="w-5 h-5 text-green-400" />
          <span className="text-green-400 font-medium">
            99.2% success rate with AI/ML detection across ALL watermark types
          </span>
        </div>
      </motion.div>
    </section>
  );
}
